### ISSUE TITLE
translation ui issues

### ISSUE THREAD

**Issue by andre68723** [adamberryhuff/sankeycash#3]
- Skip, Back and Next buttons on Instructions not translated
- Step content in instructions translation not displayed
- Diagram rendering for gross and net displays original english terms in German lang

**Comment by adamberryhuff** [comment]
> - Skip, Back and Next buttons on Instructions not translated
> - Step content in instructions translation not displayed

This is due to the JS package I am using to display the introduction. It looks like it caches it in English when the page loads. I'll need to look into how I can programmatically reset the intro when the language changes.

>  - Diagram rendering for gross and net displays original english terms in German lang

Resolved!

Leaving this issue open for now until I get a fix up for the first two bullet points.

**Comment by adamberryhuff** [comment]
> - Skip, Back and Next buttons on Instructions not translated
> - Step content in instructions translation not displayed

Resolved!
